# Let's Chat: Docker Compose
# https://docs.docker.com/compose/
#
# Usage: docker-compose up

mongo:
  image: mongo:latest

app:
  build: .
  dockerfile: Dockerfile-dev
  links:
    - mongo
  # Port fox XMPP, not necessary
  # ports:
  #   - 5222:5222
  volumes:
    - .:/usr/src/app
  environment:
    TITLE: "Hello Hanoi vietnam"

nginx:
  image: linhmtran168/node-nginx
  ports:
    - 80:80
  links:
    - app
