# Let's Chat: Docker Compose
# https://docs.docker.com/compose/
#
# Usage: docker-compose up

app:
  build: .
  dockerfile: Dockerfile-dev
  links:
    - mongo
  ports:
    - 80:8080
    - 5222:5222
  volumes:
    - .:/usr/src/app

mongo:
  image: mongo:latest
