# Let's Chat: Docker Compose
# https://docs.docker.com/compose/
#
# Usage: docker-compose up

app:
  image: linhmtran168/lets-chat:latest
  links:
    - mongo
  environment:
    GREETING: "Hello DockerCon"

mongo:
  image: mongo:latest

nginx:
  image: linhmtran168/node-nginx:latest
  links:
    - app
  ports:
    - 80:80
